% Program used to randomly generate a deck of cards, and assign the
% corresponding blackjack card value to the player's card counter

% Randomises RNG sequence used by randi
rng('shuffle');
 
% Random permutation of a deck of cards, converted to values between 1-13
n = ceil(randperm(52)/4);

% Array containing the card values for blackjack
cardValues = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 10, 10];

% Initialisation for the index value
index = 1;

% Determines the blackjack value of the card generated by random 
% permutation and assigns it to the player's card counter
PlayerCard = cardValues(n(index));

% Updates the index to draw the next card in the permutation 
index = index + 1;

disp(PlayerCard);